services:
  - type: web
    name: keycloak-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: KEYCLOAK_ADMIN
        value: will.andy
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: newLogin
      - key: KC_HOSTNAME
        value: render-deploy-t8uv.onrender.com # Replace with your actual service name
    ports:
      - 8080
